services:
  integrations-api:
    build:
      context: .
      dockerfile: src/Integrations.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: integrations-api
    container_name: integrations-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:8080"
