// <auto-generated />
using System;
using Integrations.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Integrations.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261004122207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Integrations.Api.Entities.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("Premium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EffectiveDate = new DateOnly(2026, 1, 1),
                            HolderName = "Nino Beridze",
                            PolicyNumber = "POL-1001",
                            Premium = 1250.00m
                        },
                        new
                        {
                            Id = 2,
                            EffectiveDate = new DateOnly(2026, 2, 15),
                            HolderName = "Giorgi Maisuradze",
                            PolicyNumber = "POL-1002",
                            Premium = 980.50m
                        },
                        new
                        {
                            Id = 3,
                            EffectiveDate = new DateOnly(2026, 3, 10),
                            HolderName = "Mariam Kapanadze",
                            PolicyNumber = "POL-1003",
                            Premium = 1430.75m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
